sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vladyslavjustt/bruh  -f Dockerfile.dev .

script:
  - docker run -e CI=true vladyslavjustt/bruh npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-normal-react"
  env: "Dockernormalreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-378425499128"